/*
 * ADC_config.h
 *
 *  Created on: Aug 29, 2022
 *      Author: Ahmed
 */

#ifndef REPO_MCAL_ADC_ADC_CONFIG_H_
#define REPO_MCAL_ADC_ADC_CONFIG_H_

/*
 * Configure the voltage reference
 * Range:
 * ADC_VOLTAGE_REF_AVCC
 * ADC_VOLRAGE_REF_AREF
 * ADC_VOLTAGE_REF_2_56v
 */

#define ADC_VOLTAGE_REF_SELECTOR_msk		ADC_VOLTAGE_REF_AREF

#define ADC_VOLTAGE_REF_mv					5000
#define ADC_MAX_NUMBER_OF_STEPS				1024

/*
 * Configure the ADC mode
 * Range:
 * ADC_MODE_AUTO_TRIGGER
 * ADC_MODE_SINGLE_CONVERSION
 */
#define ADC_MODE_SELECTOR					ADC_MODE_SINGLE_CONVERSION

/*
 * Configure the ADC adjustment
 * Range:
 * ADC_RIGHT_ADJUSTED
 * ADC_LEFT_ADJUSTED
 */
#define ADC_ADJUSTMENT_SELECTOR				ADC_RIGHT_ADJUSTED

/*
 * Configure the ADC prescaler
 * Range:
 * ADC_PRESCALER_CLR_MSK
 * ADC_PRESCALER_2_MSK
 * ADC_PRESCALER_4_MSK
 * ADC_PRESCALER_8_MSK
 * ADC_PRESCALER_16_MSK
 * ADC_PRESCALER_32_MSK
 * ADC_PRESCALER_64_MSK
 * ADC_PRESCALER_128_MSK
 */
#define ADC_PRESCALER_SELECTOR_MSK			ADC_PRESCALER_128_MSK

/*
 * Configure the ADC trigger source
 * Range:
 * ADC_AUTO_TRIG_SRC_CLE_MSK
 * ADC_AUTO_TRIG_SRC_FREE_RUNNING_MSK
 * ADC_AUTO_TRIG_SRC_ANALOG_COMP_MSK
 * ADC_AUTO_TRIG_SRC_EXIT0_MSK
 * ADC_AUTO_TRIG_SRC_TIMER0_COMP_MSK
 * ADC_AUTO_TRIG_SRC_TIMER0_OVF_MSK
 * ADC_AUTO_TRIG_SRC_TIMER1_COMP_MSK
 * ADC_AUTO_TRIG_SRC_TIMER1_OVF_MSK
 * ADC_AUTO_TRIG_SRC_TIMER1_CAPT_MSK
 */
#define ADC_AUTO_TRIG_SRCE_SELECTOR			ADC_AUTO_TRIG_SRC_FREE_RUNNING_MSK

#endif /* REPO_MCAL_ADC_ADC_CONFIG_H_ */
